# Generated by Django 2.1.2 on 2018-10-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181010_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='creator',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
