# Generated by Django 2.1.2 on 2018-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shorturl_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='creator',
            field=models.CharField(max_length=40),
        ),
    ]
